<?php

/**
 * Generated by OutlineTestGenerator on 2016-02-04 at 17:01:12.
 */
class FeaturesTest extends TestCase
{

    public function testGet_Fetching_credits_available_Returns_200()
    {
        $call = $this->get("/status/credits", array ( 'Authorization' => 'Token ApiKey1234', ));
        $call->seeJsonStructure(array ( 'status', 'message', 'data', 'data' => array ( 'credits_available', ), ));
        $call->assertResponseStatus(200);
    }

    public function testGet_Fetching_credits_available_Returns_402()
    {
        $call = $this->get("/status/credits", array ( 'Authorization' => 'Token ApiKey1234', ));
        $call->seeJsonStructure(array ( 'status', 'message', 'data', 'data' => array ( 'credits_available', 'min_threshold', ), ));
        $call->assertResponseStatus(402);
    }

    public function testGet_Fetching_credits_available_Returns_401()
    {
        $call = $this->get("/status/credits", array ( 'Authorization' => 'Token WrongApiKey1234', ));
        $call->seeJsonStructure(array ( 'status', 'message', ));
        $call->assertResponseStatus(401);
    }

    public function testPost_Resending_a_code_Returns_200()
    {
        $call = $this->post("/code/resend", array ( 'client_user_id' => '12345', 'phone_number' => '27848118111', ), array ( 'Content-Type' => 'application/json', 'Authorization' => 'Token ApiKey1234', ));
        $call->seeJsonStructure(array ( 'status', 'message', 'data', 'data' => array ( 'verification_status', 'expires_at', 'expires_at' => array ( 'date', 'timezone_type', 'timezone', ), ), ));
        $call->assertResponseStatus(200);
    }

    public function testPost_Resending_a_code_Returns_400()
    {
        $call = $this->post("/code/resend", array ( 'phone_number' => '27848118111', ), array ( 'Content-Type' => 'application/json', 'Authorization' => 'Token ApiKey1234', ));
        $call->seeJsonStructure(array ( 'status', 'message', ));
        $call->assertResponseStatus(400);
    }

    public function testPost_Resending_a_code_Returns_401()
    {
        $call = $this->post("/code/resend", [], array ( 'Content-Type' => 'application/json', 'Authorization' => 'Token WrongApiKey1234', ));
        $call->seeJsonStructure(array ( 'status', 'message', ));
        $call->assertResponseStatus(401);
    }

    public function testPost_Resending_a_code_Returns_406()
    {
        $call = $this->post("/code/resend", array ( 'client_user_id' => '12345', 'phone_number' => 'someBadNumber', ), array ( 'Content-Type' => 'application/json', 'Authorization' => 'Token ApiKey1234', ));
        $call->seeJsonStructure(array ( 'status', 'message', 'data', 'data' => array ( 'required_format', ), ));
        $call->assertResponseStatus(406);
    }

}
