<?php

/**
 * Generated by OutlineTestGenerator on 2016-01-20 at 10:27:20.
 */
class FeaturesTest extends TestCase
{

    public function testGet_Fetching_credits_available_Returns_200()
    {
        $this->get("/status/credits")
            ->assertResponseStatus(200);
    }

    public function testGet_Fetching_credits_available_Returns_402()
    {
        $this->get("/status/credits")
            ->assertResponseStatus(402);
    }

    public function testGet_Fetching_credits_available_Returns_401()
    {
        $this->get("/status/credits")
            ->assertResponseStatus(401);
    }

    public function testGet_Health_checking_system_Returns_200()
    {
        $this->get("/status/check")
            ->assertResponseStatus(200);
    }

}
