<?php

/**
 * Generated by OutlineTestGenerator on 2016-01-15 at 09:44:33.
 */
class FeaturesTest extends TestCase
{

    public function testGet_Fetching_credits_available_Returns200()
    {
        $this->get("/status/credits")
            ->assertResponseStatus(200);
    }

    public function testGet_Fetching_credits_available_Returns402()
    {
        $this->get("/status/credits")
            ->assertResponseStatus(402);
    }

    public function testGet_Fetching_credits_available_Returns401()
    {
        $this->get("/status/credits")
            ->assertResponseStatus(401);
    }

}
